Repository open-template-hub/file-storage-server-template, pull requests merged in 2020-09, with the labels that each got.

#3 Flows Test
  README.md
Labels: documentation

#9 response code fix
  app/routes/file.route.ts
Labels: bug

#10 Feature
  app/controllers/file.controller.ts
  app/models/file.model.ts
  app/providers/s3-file-service.provider.ts
  app/repository/file.repository.ts
  app/routes/file.route.ts
  assets/requests/file-requests.rest
Labels: enhancement

#11 request fix
  assets/requests/file-requests.rest
Labels: enhancement

#12 Fixing S3 Data Type to Base64 and S3 Content Type
  app/controllers/file.controller.ts
  app/models/file.model.ts
  app/providers/s3-file-service.provider.ts
Labels: enhancement

#14 Sonar Cloud Issues Fix
  app/controllers/file.controller.ts
  app/providers/mongo.provider.ts
  app/repository/file.repository.ts
  app/wrappers/file-service.wrapper.ts
Labels: quality

#16 Implementing is_public feature
  app/controllers/file.controller.ts
  app/models/file.model.ts
  app/repository/file.repository.ts
  assets/requests/file-requests.rest
  assets/sql/preload.tables.psql
Labels: enhancement
